version: '3.7'

services:
  mysql:
    container_name: sgm_mysql
    build: ./docker/mysql
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '${MARAIDB_PORT_3306:-3307}:3306'
    volumes:
      - ./var/mysql:/var/lib/mysql
    networks:
      - app-network
    restart: always
  nginx:
    container_name: sgm_nginx
    build: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - '${NGINX_PORT_80:-81}:80'
      - '${NGINX_PORT_443:-444}:443'
    links:
      - php-fpm
    depends_on:
      - php-fpm
    networks:
      - app-network
    restart: always
  php-fpm:
    container_name: sgm_php_fpm
    build: ./docker/php-fpm
    env_file:
      - .env
    volumes:
      - .:/var/www
    links:
      - mysql
      - python
      - redis
    depends_on:
      - mysql
      - python
    networks:
      - app-network
    restart: always
  node:
    container_name: sgm_node
    build: ./docker/node
    env_file:
      - .env
    privileged: true # TODO: fix, so we won't need it
    volumes:
      - .:/var/www
    networks:
      - app-network
    restart: always
  python:
    container_name: sgm_python
    build: ./docker/python
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - .:/var/www # Must include that one. It's needed for some unit tests
    networks:
      - app-network
    restart: always
  redis:
    container_name: sgm_redis
    image: redis
    volumes:
      - ./var/redis:/data
    networks:
      - app-network
    restart: always
  memcached:
    container_name: sgm_memcached
    image: memcached
    volumes:
      - ./var/memcached:/var/lib/memcached
    networks:
      - app-network
    restart: always
networks:
  app-network:
    name: sgm_app_network
    driver: bridge
