version: '3.7'

services:
  # Both services (php-fpm & python) MUST have the same volumes added,
  #   especially if you have .dng files or videos (needs to be implemented) in the volume
  php-fpm:
    volumes:
      - server-nfs:/var/data/server
  python:
    volumes:
      - server-nfs:/var/data/server
volumes:
  # Add your own volumes, where your data is located down below
  server-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.21.91.110,rw,soft,nolock
      device: :/srv
