version: '3.7'

services:
  mariadb:
    build: ./docker/mariadb
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app
  nginx:
    build: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "${NGINX_PORT_80}:80"
      - "${NGINX_PORT_443}:443"
    links:
      - php-fpm
    depends_on:
      - php-fpm
    networks:
      - app
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - .:/var/www
    networks:
      - app
  node:
    build: ./docker/node
    volumes:
      - .:/var/www
    networks:
      - app
  python:
    build: ./docker/python
    networks:
      - app
networks:
  app:
    driver: bridge
