version: '3'

services:
  mariadb:
    build: ./docker/mariadb
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    network_mode: host
  nginx:
    build: ./docker/nginx
    volumes:
      - ./web:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "${NGINX_PORT_80}:80"
      - "${NGINX_PORT_443}:443"
    links:
      - php-fpm
    depends_on:
      - php-fpm
    networks:
        - network
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./web:/var/www
    networks:
        - network

networks:
    network:
        driver: bridge
