version: '3.7'

services:
  # Both services (php-fpm & python) MUST (!!!) have the same volumes added,
  #   especially if you have .dng files or videos (needs to be implemented) in the volume
  php-fpm:
    volumes:
      # - /srv:/var/data/server
      # or if it's not on the same server:
      - server-nfs:/var/data/server
  python:
    ports:
      - '${PYTHON_PORT_8000:-8001}:8000'
    volumes:
      # - /srv:/var/data/server
      # or if it's not on the same server:
      - server-nfs:/var/data/server
  # For easier DB managament, let's also add PHPMyAdmin
  phpmyadmin:
    container_name: sgm_phpmyadmin
    build: ./docker/phpmyadmin
    depends_on:
      - mysql
    ports:
      - '${PHPMYADMIN_PORT_80:-82}:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    networks:
      - app-network
    restart: always
volumes:
  # Add your own volumes down below
  # This is an example of a NFS drive
  server-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.21.91.110,rw,soft,nolock
      device: :/srv
