version: '3.7'

services:
  nginx:
    container_name: sgm_nginx
    build: ./docker/nginx
    privileged: true
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "${NGINX_PORT_80:-81}:80"
      - "${NGINX_PORT_443:-444}:443"
    links:
      - php-fpm
    depends_on:
      - php-fpm
    networks:
      - app-network
  php-fpm:
    container_name: sgm_php_fpm
    build: ./docker/php-fpm
    privileged: true
    volumes:
      - .:/var/www
      # Add your own data below, inside the /var/data directory, for example:
      # - server-nfs:/var/data/server
      - server-nfs:/var/data/server
    links:
      - python
    depends_on:
      - python
    networks:
      - app-network
  node:
    container_name: sgm_node
    build: ./docker/node
    privileged: true
    volumes:
      - .:/var/www
    networks:
      - app-network
  python:
    container_name: sgm_python
    build: ./docker/python
    privileged: true
    volumes:
      - .:/usr/src/app
      # Read the comment above in php-fpm.volumes. They MUST be the same paths!!!
      - server-nfs:/var/data/server
    ports:
      - "${PYTHON_PORT_8000:-8001}:8000"
    networks:
      - app-network
networks:
  app-network:
    name: sgm_app_network
    driver: bridge
volumes:
  # Add your own volumes, where your data is located down below
  server-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.21.91.110,rw,soft,nolock
      device: :/srv
