version: '3.7'

services:
  # Both services (php-fpm & python) MUST have the same volumes added,
  #   especially if you have .dng files or videos (needs to be implemented) in the volume
  php-fpm:
    volumes:
      - server-nfs:/var/data/server
  python:
    volumes:
      - server-nfs:/var/data/server
  # In case you choose redis & memcached for the FILES_CACHE_ADAPTER
  redis:
    container_name: sgm_redis
    image: redis
    volumes:
      - ./var/redis:/data
    networks:
      - app-network
    restart: always
  memcached:
    container_name: sgm_memcached
    image: memcached
    volumes:
      - ./var/memcached:/var/lib/memcached
    networks:
      - app-network
    restart: always
  # For easier DB managament, let's also add PHPMyAdmin
  phpmyadmin:
    container_name: sgm_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - '${PHPMYADMIN_PORT_80:-82}:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-network
    restart: always
volumes:
  # Add your own volumes, where your data is located down below
  server-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.21.91.110,rw,soft,nolock
      device: :/srv
