web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler:
        only_exceptions: false
        # TODO: No idea why simply %env(CACHE_DIR)% doesn't work
        dsn: 'file:%kernel.project_dir%/../var/cache/profiler'
