doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                json_unquote: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonUnquote
                json_extract: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
                json_contains: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
                json_array: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonArray
            datetime_functions:
                date: DoctrineExtensions\Query\Mysql\Date
                month: DoctrineExtensions\Query\Mysql\Month
                year: DoctrineExtensions\Query\Mysql\Year
                date_format: DoctrineExtensions\Query\Mysql\DateFormat
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
