parameters:
    allowed_image_conversion_types:
        thumbnail:
            height: 64
        preview:
            height: 240
        original: ~
    max_age: 3600 # how long will the image exist, until it expires/needs refreshing?
    cache_dir: '%kernel.project_dir%/../var/cache'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    admin.file:
        class: App\Admin\FileAdmin
        arguments: [~, App\Entity\File, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: 'File'
              pager_type: 'simple'
              group: General
