parameters:
    # General
    var_dir: '%kernel.project_dir%/../var'
    allowed_image_conversion_types:
        thumbnail:
            height: 64
        preview:
            height: 240
        original: ~
    image_max_age: 3600 # how long will the image exist, until it expires/needs refreshing?

    # Geocoding
    geocoding_enabled: true
    here_reverse_geocoder_radius: 500
    here_reverse_geocoder_max_results: 32
    here_api_credentials:
        app_id: '%env(HERE_APP_ID)%'
        app_code: '%env(HERE_APP_CODE)%'

    # Labeling
    labeling_enabled: true
    # The difference between "labeling_confidence" and "aws_rekognition_min_confidence" is,
    #   that "aws_rekognition_min_confidence" will fetch all tags above that confidence,
    #   and save/cache it then in a json file, which will be then processed,
    #   and the found labels will be saved to "tags" in the database.
    # This is where the "labeling_confidence" comes in. That is then used to determine
    #   which labels should be into the tags, so you could re-run the scanning
    #   without needing to re-fetch from AWS. Means, you can set the "aws_rekognition_min_confidence"
    #   as low as possible, and then set "labeling_confidence" as high as you need it.
    # You can still change it then if you want.
    labeling_confidence: 75 # Percentage, from 0-100
    aws_rekognition_region: 'eu-central-1'
    aws_rekognition_version: 'latest'
    aws_rekognition_min_confidence: 55 # Percentage, from 0-100
    aws_credentials:
        key: '%env(AWS_KEY)%'
        secret: '%env(AWS_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    admin.file:
        class: App\Admin\FileAdmin
        arguments: [~, App\Entity\File, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: 'File'
              pager_type: 'simple'
              group: General
