parameters:
    # General
    var_dir: '%kernel.project_dir%/../var'
    allowed_image_conversion_types:
        thumbnail:
            height: 64
        preview:
            height: 240
        original: ~
    files_cache_adapter: '%env(FILES_CACHE_ADAPTER)%'

    # Geocoding
    geocoding_enabled: '%env(bool:GEOCODING_ENABLED)%'
    geocoding_service: '%env(GEOCODING_SERVICE)%'
    here_reverse_geocoder_radius: '%env(int:HERE_REVERSE_GEOCODER_RADIUS)%'
    here_reverse_geocoder_max_results: '%env(int:HERE_REVERSE_GEOCODER_MAX_RESULTS)%'
    here_app_id: '%env(HERE_APP_ID)%'
    here_app_code: '%env(HERE_APP_CODE)%'

    # Labeling
    labelling_enabled: '%env(bool:LABELLING_ENABLED)%'
    labelling_service: '%env(LABELLING_SERVICE)%'
    labelling_confidence: '%env(bool:LABELLING_CONFIDENCE)%'
    amazon_rekognition_region: '%env(AMAZON_REKOGNITION_REGION)%'
    amazon_rekognition_version: '%env(AMAZON_REKOGNITION_VERSION)%'
    amazon_rekognition_min_confidence: '%env(int:AMAZON_REKOGNITION_MIN_CONFIDENCE)%'
    aws_key: '%env(AWS_KEY)%'
    aws_secret: '%env(AWS_SECRET)%'

    # Faces
    faces_enabled: '%env(bool:FACES_ENABLED)%'
    faces_service: '%env(FACES_SERVICE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(resolve:DATABASE_URL)%'

    # Admin
    admin.file:
        class: App\Admin\FileAdmin
        arguments: [~, App\Entity\File, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: 'File'
              pager_type: 'simple'
              group: General

bazinga_geocoder:
    providers:
        here:
            factory: Bazinga\GeocoderBundle\ProviderFactory\HereFactory
            cache: 'cache.app.simple'
            cache_lifetime: 3600
            cache_precision: 8
            options:
                app_id: '%here_app_id%'
                app_code: '%here_app_code%'
