parameters:
    # General
    var_dir: '%kernel.project_dir%/../var'
    allowed_image_conversion_types:
        thumbnail:
            height: 64
        preview:
            height: 240
        original: ~
    files_cache_adapter: '%env(FILES_CACHE_ADAPTER)%'

    # Geocoding
    geocoding_enabled: '%env(bool:GEOCODING_ENABLED)%'
    geocoding_service: '%env(GEOCODING_SERVICE)%'
    here_reverse_geocoder_radius: '%env(int:HERE_REVERSE_GEOCODER_RADIUS)%'
    here_reverse_geocoder_max_results: '%env(int:HERE_REVERSE_GEOCODER_MAX_RESULTS)%'
    here_api_credentials:
        app_id: '%env(HERE_APP_ID)%'
        app_code: '%env(HERE_APP_CODE)%'

    # Labeling
    labelling_enabled: '%env(bool:LABELLING_ENABLED)%'
    labelling_confidence: '%env(bool:LABELLING_CONFIDENCE)%'
    amazon_rekognition_region: '%env(AMAZON_REKOGNITION_REGION)%'
    amazon_rekognition_version: '%env(AMAZON_REKOGNITION_VERSION)%'
    amazon_rekognition_min_confidence: '%env(int:AMAZON_REKOGNITION_MIN_CONFIDENCE)%'
    aws_credentials:
        key: '%env(AWS_KEY)%'
        secret: '%env(AWS_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    admin.file:
        class: App\Admin\FileAdmin
        arguments: [~, App\Entity\File, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: 'File'
              pager_type: 'simple'
              group: General
